
version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 588792668449.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=588792668449.dkr.ecr.ap-south-1.amazonaws.com/webapp
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - aws ecs list-tasks --cluster default --output text | awk '{print $2}' | while read line ; do aws ecs stop-task --task "$line" --cluster default ; done
      - printf '[{"name":"your.task.definition.name","imageUri":"%s"}]' 588792668449.dkr.ecr.ap-south-1.amazonaws.com/$REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
  artifacts:
    files:
      - imagedefinitions.json
      - '**/*'
